package com.E389_Find_the_Difference;

import java.util.*;

/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter 
at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.*/

public class E389_Find_the_Difference {

	public static void main(String[] args) {
		String inputS = "abcd", inputT = "abtcd";
        char output = findTheDifference(inputS, inputT);
        System.out.println("inputS: " + (inputS) + " / inputT: " + (inputT) + "\noutput: " + (output));
	}
	
	/*
    solution:
    遍历两个字符串，计算两个字符串当中所有字符的Ascll码之和的差值，结果差值对应的字符就是新增的字符
    */
	
	/*
     * @param s: a string
     * @param t: a string
     * @return: the letter that was added in t
     */
	public static char findTheDifference(String s, String t) {
		int flag = 0;
		
		for(int i = 0; i < s.length(); i++) {
			flag += (t.charAt(i) - s.charAt(i));
		}
		flag += t.charAt(t.length() - 1);
		
		return (char)flag;
	}

}
